Add Quilt support
Infinidoge/nix-minecraft pull request #1
Opened 2022-06-25 22:40 UTC by leo60228

This was based on the Fabric support, with the necessary changes maded.

2022-06-26 07:23 UTC, Infinidoge commented
Thank you very much for the contribution!

If possible, please change the commit message to something along the lines of `feat(quilt-servers): init`, since that would better fit with the conventions I've used so far.

2022-06-26 07:46 UTC, Infinidoge requested changes
Overall looks good! Please run `update.py` through `black` though, as it would help with keeping a consistent code style. (Note to self, make a `CONTRIBUTING.{md,org}`)

2022-06-26 07:46 UTC, Infinidoge commented on pkgs/quilt-servers/update.py
> +    return tuple(map(int, (v.partition("-")[0].split("."))))
What particular cases in the API motivated changing this from `+` to `-`? I assume for parsing `1.18.2-pre1`, etc?

The `+` filtering in there was originally to remove the build number information from version numbers, so perhaps this should be updated to be consistent with the Fabric version.

(I might extract the common functions between the `update.py` files, but for now leaving them in their own files is fine; Makes it easy to be self-contained.)

2022-06-26 07:46 UTC, Infinidoge commented on pkgs/quilt-servers/server.nix
> +  exec ${jre_headless}/bin/java $@ -jar ${loader} nogui''
I assume the `log4j` XML file not necessary for Quilt?

2022-06-26 07:46 UTC, Infinidoge commented on pkgs/quilt-servers/loader.nix
> +  '';
Roughly here is where in the Fabric file, there is
```nix
cat > fabric-server-launch.properties << EOF
launch.mainClass=${lock.mainClass}
EOF
```
I assume that this is unnecessary for Quilt?

2022-06-26 07:46 UTC, Infinidoge commented on pkgs/quilt-servers/default.nix
> +  merge = null;
I honestly have no idea why I included this in the Fabric `default.nix`. Probably had a function there but forgot to remove it.

Feel free to remove it, and add an additional commit removing it from the Fabric side, as it (theoretically, hopefully...) is unimportant.

2022-06-26 07:46 UTC, Infinidoge commented on pkgs/quilt-servers/update.py
> +        return tuple(map(int, snapshotmatch.groups())) >= (22, 11)
Is there a particular reason why the game versions are constrained to `>= 1.18.2` and `>= 22w11x`?

I would assume that, though maybe not the best quality, all versions reported by the Quilt API would/should be supported, similar to what is done in the Fabric `update.py`

2022-06-26 07:46 UTC, Infinidoge commented on pkgs/quilt-servers/update.py
> +    snapshotmatch = re.fullmatch('([0-9]{2})w([0-9]{1,2})[a-z]+', version["version"])
This regular expression should be declared up top as a constant with `re.compile`, as doing it like this will recompile the regular expression on each use, slowing things down slightly.

2022-06-26 07:48 UTC, Infinidoge commented on README.org
> +** ~quiltServers.*~
Please also add a `Source` link here, like the Fabric and Vanilla server sections.

2022-06-27 02:34 UTC, leo60228 commented on pkgs/quilt-servers/update.py
> +    return tuple(map(int, (v.partition("-")[0].split("."))))
Quilt uses version numbers like `0.16.0-beta.2`.

2022-06-27 02:34 UTC, leo60228 commented on pkgs/quilt-servers/loader.nix
> +  '';
Yep, the Quilt installer doesn't create it and it didn't seem to be necessary during testing.

2022-06-27 02:35 UTC, leo60228 commented on pkgs/quilt-servers/update.py
> +        return tuple(map(int, snapshotmatch.groups())) >= (22, 11)
1.18.2 was the current version as of Quilt's initial beta release, and I'm not sure how far back quilt-loader will still function. (Additionally, I didn't want to wait for every version to download)

2022-06-27 02:38 UTC, leo60228 commented on pkgs/quilt-servers/server.nix
> +  exec ${jre_headless}/bin/java $@ -jar ${loader} nogui''
1.18.2+ already have secure log4j versions, don't they?

2022-06-27 02:48 UTC, Infinidoge commented
Another small thing I noticed, could you add to the README to change 
> along with versions for the Fabric loader

into
> along with versions for the Fabric and Quilt loaders

?

2022-06-27 02:53 UTC, Infinidoge commented on pkgs/quilt-servers/update.py
> +    return tuple(map(int, (v.partition("-")[0].split("."))))
Ah, I see, makes sense.

2022-06-27 02:55 UTC, Infinidoge commented on pkgs/quilt-servers/server.nix
> +  exec ${jre_headless}/bin/java $@ -jar ${loader} nogui''
That is true. I don't know enough about log4j to know everything about what the file does, but I assume that the `Appenders` section is to recreate Vanilla behavior, while the `Loggers` section fixes the log4j exploit?

2022-08-01 20:47 UTC, imsofi commented
Friendly poke to see if this is still being worked on, i can help with adding some commits to this if help is needed.

2022-08-21 04:37 UTC, Infinidoge commented
Superseded by #7

2022-08-21 04:37 UTC, closed without merging