feat: add paper server packages
Infinidoge/nix-minecraft pull request #21
Opened 2023-01-07 18:50 UTC by Misterio77

Package all paper servers.

2023-01-07 19:21 UTC, Misterio77 commented on pkgs/paper-servers/update.py
> +def make_client():
I had to add some timeout and retries, as it seems the papermc api is a bit unstable (at least on my machine) and often hangs.

2023-01-07 19:21 UTC, Misterio77 commented on pkgs/paper-servers/update.py
> +    main(open(lock_path, "w"), make_client())
I decided to write the lock from scratch every time, as it takes only about 12 seconds to do so (there's much fewer builds when compared to fabric).

2023-01-07 19:21 UTC, Misterio77 commented on pkgs/paper-servers/default.nix
> +  latestBuilds = sortBy "version" versionOlder (map last packages);
My approach for getting the latest build for each MC version was making a nested list and grabbing the first of each. `packages` looks something like this (each element being a derivation): 
```
[ [ paper-1.17.1-build.1 paper-1.17.1-build.2 ... ] [ paper-1.18-build.1 paper-1.18-build.2 ... ] ... ]
```

2023-01-08 04:38 UTC, Infinidoge commented on pkgs/paper-servers/update.py
> +def make_client():
Darn you unstable APIs!
That being said, definitely a good idea to have.

2023-01-08 04:39 UTC, Infinidoge commented on pkgs/paper-servers/update.py
> +    main(open(lock_path, "w"), make_client())
Makes sense, Fabric/Quilt definitely have a lot more builds with the sheer number of loader version/minecraft version combinations.

2023-01-08 04:40 UTC, Infinidoge requested changes
Looks good overall!

That being said, the README needs to be updated to reflect the changes before this can be merged.

Once that's done, I'll smoke test before merging.

2023-01-13 17:40 UTC, merged