Implement Velocity Proxy server module
Infinidoge/nix-minecraft pull request #47
Opened 2023-10-24 01:25 UTC by scottbot95

Implement Velocity Proxy server module. 

It's basically just a special-purpose version of the minecraft-servers module. We probably could just use the minecraft-servers module but some properties (specifically `serverProperties` and `whitelist`) don't really make any sense for Velocity.

2023-10-24 14:50 UTC, Infinidoge requested changes
Overall looks good! I assume this has been tested in your setup and works well?

The main thing I would like before merging this would be to have it run through `nixpkgs-fmt`, as that is the main formatter I use. (I really should add more documentation to the repo for stuff like that...)

2023-10-24 14:50 UTC, Infinidoge commented on flake.nix
> +      };
Good call, I didn't think about making default import everything.

2023-10-24 14:50 UTC, Infinidoge commented on modules/velocity.nix
> +    config = {
I assume these options use `dashed-case` as opposed to `camelCase` to match the velocity config?

2023-10-24 14:50 UTC, Infinidoge commented on modules/velocity.nix
> +          <option>services.minecraft-servers.servers</option>
If it is possible, documenting a way to both auto-generate and specify would be nice.

2023-10-24 18:15 UTC, scottbot95 commented on modules/velocity.nix
> +          <option>services.minecraft-servers.servers</option>
Hmmm interesting idea. I could make the default be an auto-generated attribute set instead of `null`. The downside to that approach is I'm pretty sure that means users wouldn't be able remove the auto-generated servers (although perhaps `mkForce` would work?)

2023-10-24 18:16 UTC, scottbot95 commented on modules/velocity.nix
> +    config = {
Correct. The config here is just the config values from Velocity mapped to nix types.

2023-10-24 18:17 UTC, scottbot95 commented on flake.nix
> +      };
Yeah it's a somewhat common pattern when you start having flakes with multiple modules exported. I added this cuz I was too lazy to have multiple imports in my consuming flake lol.

2023-10-24 18:19 UTC, scottbot95 commented
I can run the formatter. Might take me a day or two before I can get back to this. I've also seen other flakes that include a style check in the actual flake checks so you can setup some GH actions to run `flake check` and it will fail if the files aren't properly formatted. I will take a look at how that's implemented. If it's easy enough I might just include it in this PR as well (or a separate PR).

2023-12-14 18:07 UTC, Misterio77 commented
Hi! I have some thoughts on this:

- This can and should be implemented through `minecraft-server.servers.*` instead of `systemd.services.*` directly. The rule of thumb is: always use the higher-level abstraction you can get away with using.
  - I'm pretty sure `velocity.toml` **has** to be mutable. Or it'll blow up in the slightest change or missing key.
  - You're missing on super important features such as `files` and `symlinks`, which you can, by the way, use to implement `config` instead of manually linking `configFile`.
  - Due to that, there's a huge amount of duplicated code. This means improvements to `minecraft-server.servers` are not available here, and increases maintenance burden.
-  Mapping all options like that is a major footgun for maintenance. I recommend using [the `settings` pattern](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) instead. 
    - What if options change between versions? They do change a lot. Will we have to actively hunt for velocity changelogs and add dozens of version checks and warnings for deprecation? This quickly gets out of hand.
    - As an example, you're missing `player-info-forwarding-mode`.

I hate to be this person but, I don't think we should add specialized modules. Minecraft network setups vary a lot (what if they want two proxies? etc). We should focus effort in improving the base module while always keeping module complexity in check. Most of this is already possible (the convenience is very, very small):
```nix
services.minecraft-servers.servers.velocity = {
  enable = true;
  package = pkgs.velocity-server;
  files."velocity.toml".value = {
    bind = "0.0.0.0:25565";
    forwarding-secret-file = ...;
    servers = (mapAttrs (_: v: "localhost:${toString v.serverProperties.server-port}") config.minecraft-servers.servers) // {
      try = [ "foo" ];
    };
  };
};
```
VS
```nix
services.minecraft-servers.velocity = {
  enable = true;
  address = "0.0.0.0";
  port = 25565;
  forwarding-secret-file = ...;
  config.try = [ "foo" ];
};
```

If we're sure we want a specialized variant, it should be a very, very thin wrapper around `minecraft-servers.servers`.

2024-12-29 21:43 UTC, Infinidoge commented
Sorry for not getting to this earlier, university was very busy and draining for me this past year. After looking at this again, I agree with Misterio that this is better left to `minecraft-servers.servers`. The only thing that isn't currently possible with the existing module is automatically generating the secret.

Following from that, I'm closing this PR. Thank you for the contribution, though!

2024-12-29 21:43 UTC, closed without merging