Transfer documentation from module to README
Infinidoge/nix-minecraft pull request #59
Opened 2024-01-29 14:09 UTC by Silverdev2482

I think this is mostly good but I'm not sure about the syntax of how I named options, I also wouldn't be suprised as if there are a few spelling errors. It still need proofreading by me too.

2024-01-29 14:14 UTC, Silverdev2482 commented
Will `servers.<name.files` Only place non existing files, or will it overwrite them? I would like to specify that in the README.

2024-01-29 17:34 UTC, Silverdev2482 commented
Looking at it I believe it will put the files into a .bak when modified, but will overwrite the previous.bak file, if I am wrong please correct me.

2024-02-12 00:02 UTC, Infinidoge requested changes
Thanks for putting in the work of putting it into the file. I'm not too happy with how it is all laid out, but that is mostly my fault for how it is documented. Something I want to look into for the future would be generating the documentation like how it is done in Nixpkgs et al., as that would be the best solution.

Most of the suggestions are things that can just be committed as-is, let me know if you have any thoughts on them.

2024-02-12 00:02 UTC, Infinidoge commented on README.md
> +Things to copy into this server's data directory. Similar to symlinks, but these are actual files. Useful for configuration files that don't behave well when read-only.
`files` also has the option for generating files from data, which would be useful to document. CC @Misterio77 for advice on that.

2024-02-12 01:00 UTC, Silverdev2482 commented
All suggestions look good to me, I wasn't too sure on format/syntax so I went to what seems the most similar with the existing readme. Not sure if I feel like documenting the files option, as I don't have the best understanding of the nix language. If @Misterio77 feels like documenting that we should wait, or maybe a make separate issue and pr. Other than that this seems all good to merge.

2024-02-12 01:05 UTC, BatteredBunny reviewed
Noticed a typo

2024-02-12 01:05 UTC, BatteredBunny commented on README.md
> +#### `servers.<name>.package`
I'm assuming this is supposed to be ``jvmOpts`` instead?

2024-02-12 04:46 UTC, Infinidoge commented on README.md
> +#### `servers.<name>.package`
Surprised I didn't notice that, good catch.
```suggestion
#### `servers.<name>.jvmOpts`
```

2024-02-13 13:36 UTC, Silverdev2482 commented
Should that issue be created and this merged? Or do we add that to this PR and wait for it to be documented?

2024-07-11 22:06 UTC, Silverdev2482 commented
don't mean any disrespect, but should we just merge this now? If I am not mistaken there isn't anything I need to do, and Misterio hasn't responded. Every other suggestion looks fine and has been approved.

2024-07-11 22:24 UTC, Infinidoge commented
Sorry for the wait, summer has been pretty busy for me so even though this is small and straight forward, it kept getting pushed back by the other things I've been doing.

2024-07-11 22:24 UTC, merged