module: use user and group from configuration
Infinidoge/nix-minecraft pull request #61
Opened 2024-03-25 01:30 UTC by jackwilsdon

Previously, `cfg.user` and `cfg.group` were not used for the actual systemd service. This commit fixes this and also disables creation of the `minecraft` user and group if the user and group are changed.

2024-03-25 04:52 UTC, Infinidoge requested changes
I am... honestly not sure how I never noticed that fact. Configuring the user/group was definitely an afterthought, since I never needed to do that personally, but it not actually doing the important part of creating that user and using it for the service is a little bit embarrassing.

Good catch!

2024-03-25 04:52 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +          users.minecraft = mkIf (cfg.user == "minecraft") {
It might be better if this was `users.${cfg.user}` instead of disabling it outright.

2024-03-25 04:52 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +          groups.minecraft = mkIf (cfg.group == "minecraft") { };
See previous comment, this might be better as `groups.${cfg.group}` instead.

2024-03-25 04:52 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +                  Group = cfg.user;
```suggestion
                  Group = cfg.group;
```

2024-03-25 09:38 UTC, jackwilsdon commented on modules/minecraft-servers.nix
> +          users.minecraft = mkIf (cfg.user == "minecraft") {
Services that allow configuring user/group usually allow the user to create them if they specify a non-default value, e.g.:

https://github.com/NixOS/nixpkgs/blob/3b597532faf630d5053fe1072d36c4de4f773609/nixos/modules/services/misc/forgejo.nix#L634-L645

2024-03-25 09:39 UTC, jackwilsdon commented on modules/minecraft-servers.nix
> +                  Group = cfg.user;
:facepalm: fixed

2024-03-25 13:24 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +          users.minecraft = mkIf (cfg.user == "minecraft") {
Makes sense. It would probably be a good idea to add an assertion that the group/user exists then, if there is precedent for that in Nixpkgs. (I suppose mutable users makes that a bit messy)

2024-03-26 20:55 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +          users.minecraft = mkIf (cfg.user == "minecraft") {
From what I've seen that is the case, yeah. This should be fine as-is then.

2024-03-26 20:55 UTC, Infinidoge approved these changes

2024-03-26 20:56 UTC, merged