module: allow management via systemd socket
Infinidoge/nix-minecraft pull request #67
Opened 2024-06-05 22:29 UTC by frantisekhanzlikbl

Supersedes #52. Partially fixes #63.

This PR adds a way to make servers managed via a systemd stdin socket and the journal, allowing for a better integrated experience with the rest of the system.

This PR largely builds on top of @Misterio77's excellent #52 and retains the nice additions:
* expanded tests verifying automated command execution
* extra lifecycle hooks for the server services

I did change the default systemd socket path from #52 to be aligned with the current tmux socket path and renamed the lifecycle hooks to preserve the systemd naming convention, though.

I've added a few extras, not all of which I'm sure want to be kept. Feedback welcome. :slightly_smiling_face:
* `docsAsciiDoc` and `docsCommonMark` package outputs (not present in the overlay) to make sure that `nix flake check` verifies that the docs can be built. there was a trivial issue previously, which prevented them from building.
* VS Code config for [nix-ide] specifying the formatter to be `nixpkgs-fmt`, along with the proper indentation.
* per-server management of the socket (both tmux & systemd) paths.

I'm not too sure I like the way server overrides of the global management system config works, but it was all I could conjure with my limited knowledge of advanced usage of the module system.

This PR should be backwards compatible, although some field-testing would be much appreciated as I don't have any real setup to test it on (and frankly no time either :)).

2024-06-07 03:50 UTC, Infinidoge requested changes
Overall the implementation looks good! Left some notes with regards to backwards compatibility and documentation. I'll test and do further review on the code later when I have more time.

With that said, something that you should do before this can be merged is split this up into commits with separate concerns. Namely:
- The vscode settings file should be a meta commit
- Documentation export should be its own commit
- Extra pre/post start/stop and custom stop command should be its own commit
- Adding/modifying the tests should be their own commits

2024-06-07 03:50 UTC, Infinidoge commented on modules/minecraft-servers.nix
> -
For the sake of backwards compatibility, this option should be kept, with a warning if it is changed from the default. (And it should accordingly be used in the default tmux socket path function.

2024-06-07 03:50 UTC, Infinidoge commented on modules/minecraft-servers.nix
> -            <literal>"no"</literal> and <literal>"always"</literal> may not work properly.
This should be edited to maintain the note that values other than `no` and `always` may not work properly with tmux sockets.

2024-06-07 10:18 UTC, frantisekhanzlikbl commented
Thanks so much for the review!

I just pushed the requested changes. Please let me know if there is something else to change.

2024-06-07 13:19 UTC, frantisekhanzlikbl commented
Hmm, I just tried to migrate my config to this and got bitten in my ass by the extra lifecycle hooks not having `set -euo pipefail`, therefore "succeeding" even if parts of them fail. Would you mind me using `writeShellApplication` instead of `writeShellScript` for them?

This would theoretically be a breaking change, as setups previously "working" might now start failing, but I'd argue that these were broken from the start. I could add an option for that, but I don't think it would be worth the extra code and maintenance.

2024-06-07 19:48 UTC, Infinidoge requested changes
The single period change in CHANGELOG looks out of place on the diff, but also I don't think it's big enough to warrant its own commit so it can stay.

Something that I'm a bit mixed about is how which system to use is selected. Needing to explicitly turn off the default and turn on the one you want feels... wrong to me, so an enum option like
```nix
{
  system = "tmux"
  tmux.socketPath = name: ...;
}
```
might be better. This would also alleviate the need for assertions to prevent selecting 2 at the same time, with the cost of it being not idiomatic. If anyone has any thoughts about this, please chime in and tell me my code conciseness perfectionism is on the loose again.

With regards to pipefail, yeah go right ahead. These kinds of scripts should fail early, and is the kind of breaking change that should lead to more fixed problems than actual problems.

Some other small comments about module assertions and docs. Haven't tested it myself yet, but will review again after I do.

2024-06-07 19:48 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +      Plase use <option>services.minecraft-servers.managementSystem.tmux.socketPath</option>` instead.
This should have a corresponding [module system warning](https://nixos.org/manual/nixos/unstable/#sec-assertions). This would work:
```
warnings = lib.optional (cfg.runDir != "/run/minecraft") ''
  `runDir` has been deprecated.

  Please use `services.minecraft-servers.managementSystem.tmux.socketPath` instead.
  For example, `name: "${cfg.runDir}/''${name}.sock"`

  See the changelog file for more information.
'';
```
Otherwise end users who don't check this repo every so often won't get the message.

2024-06-07 19:48 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +            press `Ctrl + b` then `d` to detach.
Could you add a note here that the default will change to be `name: "/run/minecraft/${name}.sock`" after `runDir` gets removed?

2024-06-07 19:48 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +              for example with shell redirection: `echo 'list' > <path to socket>`.
Same as previous comment, would like a note stating that the default will be changing, just so its documented.

2024-06-07 19:48 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +    assert assertMsg (!(ms.tmux.enable && ms.systemd-socket.enable)) "Only one server management system can be enabled at a time.";
This should be done with a [module system assertion](https://nixos.org/manual/nixos/unstable/#sec-assertions) instead. Which actually, I'm pretty sure can be handled in the `managementSystem` submodule type, which would be clean.

2024-06-07 19:48 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +      } else builtins.throw "At least one server management system must be enabled.";
Same as previous, this would be best handled with a module system assertion.

2024-06-07 19:50 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +      Plase use <option>services.minecraft-servers.managementSystem.tmux.socketPath</option>` instead.
ouch, I totally forgot about that. sorry, I'll add it shortly. :sweat_smile:

2024-06-07 19:52 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +    assert assertMsg (!(ms.tmux.enable && ms.systemd-socket.enable)) "Only one server management system can be enabled at a time.";
I thought about that, but for some reason decided against it. I honestly don't remember why, and if it works at the submodule level, I don't see why not.

2024-06-07 21:09 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +    assert assertMsg (!(ms.tmux.enable && ms.systemd-socket.enable)) "Only one server management system can be enabled at a time.";
Oh, I know. Doing the validation as a module system assertion at the submodule level prevents the user from having `{ tmux.enable = false; systemd-socket.enable = false; }` in the global config and then choosing for each server. It might be too niche of a use case, but I can very much see myself doing this.

2024-06-07 21:15 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +      } else builtins.throw "At least one server management system must be enabled.";
Even if this one is handled via the module system assertions, this throw must stay here too, as we really don't have any meaningful return value if no management system is enabled and returning an arbitrary one feels really wrong.

2024-06-07 21:24 UTC, frantisekhanzlikbl commented
Alright, I just pushed the next iteration. Sorry about the dot change in the changelog, that might've been a little too pedantic of me. I updated the descriptions of socket path options and moved to `writeShellApplication`.

I thought about using a string enum for the preferred management system too, but decided against it, as it would make it non-practical to add more management systems (such as RCON), that don't conflict with others. i.e. both systemd-socket and tmux could be used along with RCON, just not with each other.

I kept the language-level assertions for now, for the reasons described in my comment on the appropriate review comments, but I don't feel that strongly about the first one. If you do, I can change that.

2024-06-07 21:54 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +      } else builtins.throw "At least one server management system must be enabled.";
The module system assertion would force at least 1 management system to be enabled, since it would refuse to finish evaluating otherwise.

2024-06-07 22:39 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +      } else builtins.throw "At least one server management system must be enabled.";
I believe that is only true for evaluating entire NixOS configurations. i.e. things that evaluate the top-level system attribute[^1]. Any uses of the module system that do not need to do that would not inform the user of anything, and just silently produce nonsense. a good example would be manually evaluating a part of a NixOS config in the REPL during debugging, which I do fairly often.

[^1]: https://github.com/NixOS/nixpkgs/blob/db4bd243ca966a89a2bead2f9275d9163268d856/nixos/modules/system/activation/top-level.nix#L66

2024-06-07 23:29 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +      } else builtins.throw "At least one server management system must be enabled.";
Fair. We'll just leave it as is then/

2024-06-07 23:30 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +    assert assertMsg (!(ms.tmux.enable && ms.systemd-socket.enable)) "Only one server management system can be enabled at a time.";
Makes sense. It feels unclean, but doesn't really need to be perfect, and it works as is.

2024-06-11 15:43 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +      warnings = lib.optional (cfg.runDir != options.services.minecraft-servers.runDir.default) ''
Hmm. How does this interact with `mkDefault`? If someone used `mkDefault`, then this might not warn them of the change.

2024-06-11 18:44 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +      warnings = lib.optional (cfg.runDir != options.services.minecraft-servers.runDir.default) ''
I believe that `mkDefault` is just a normal value just like any other for the module system and does not affect the default at all. There doesn't seem to be anything special about its implementation: https://github.com/NixOS/nixpkgs/blob/bc3cfcb6ed2167858598d316683f1d40ca322898/lib/modules.nix#L1014-L1020

2024-06-11 18:45 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +      warnings = lib.optional (cfg.runDir != options.services.minecraft-servers.runDir.default) ''
Ah yep, just an override with priority, nevermind!

2024-06-18 19:47 UTC, frantisekhanzlikbl commented
I just remembered that systemd has its own options for timeouts, so I pushed a new commit that lets systemd handle server stop timeouts instead of the ad-hoc implementation that was in place previously in the systemd-socket management system (and completely missing in the tmux one).

2024-09-21 15:13 UTC, marek-rychly commented
What is the status of this merge request? Can it be merged?

Logging into journald is much more better than tmux for monitoring a server, so I am using the last commit from this merge request now. Unfortunately, there are newer fabric versions in the master branch which are not available here. Rebase or merge to the master would be appreciated. Thank you.

2024-09-21 15:37 UTC, frantisekhanzlikbl commented
> What is the status of this merge request? Can it be merged?
> 
> Logging into journald is much more better than tmux for monitoring a server, so I am using the last commit from this merge request now. Unfortunately, there are newer fabric versions in the master branch which are not available here. Rebase or merge to the master would be appreciated. Thank you.

I believe all the brought up concerns have been resolved on my side.

I've been using the latest commit here on a few small-scale servers in production for about three months and have faced no problems, but my deployments are also probably fairly simple.

Currently, I'm severely short on time, so if @Infinidoge has more change requests before this is mergeable, the PR will most likely have to wait for a while or get taken up by somebody else. I'll do a rebase in the meantime, though.

2024-09-22 23:03 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +            while server_running; do sleep 1s done
```suggestion
            while server_running; do sleep 1s; done
```

2024-09-22 23:07 UTC, Infinidoge approved these changes

2024-09-22 23:07 UTC, Infinidoge commented
Note to self: GitHub action that runs `nix flake check`

2024-09-22 23:08 UTC, merged

2024-09-22 23:08 UTC, frantisekhanzlikbl commented on modules/minecraft-servers.nix
> +            while server_running; do sleep 1s done
ouch, dumb mistake. sorry and thanks for catching it. :)

2024-09-22 23:11 UTC, frantisekhanzlikbl commented
thanks for the reviews and merge, it is greatly appreciated! :)

2024-09-22 23:29 UTC, Infinidoge commented on modules/minecraft-servers.nix
> +            while server_running; do sleep 1s done
No problem :)

I should definitely add CI since this could have been caught sooner by just having GH run `nix flake check`. It's on my I'll Do It Eventually list

2024-09-23 01:30 UTC, Misterio77 commented
Thanks so much for picking this up! Looks awesome.