Dynamically set the asm version
Infinidoge/nix-minecraft pull request #85
Opened 2024-07-24 13:13 UTC by mechan1sm

Added the small workaround to extract the asm version from list of libaries to the [mkTextileLoader.nix](https://github.com/mechan1sm/nix-minecraft/blob/master/pkgs/build-support/mkTextileLoader.nix#L19).

The list of libraries must contain exactly one string matching the following regular expression:
```nix
"org\\.ow2\\.asm:asm:([\.0-9]+)"
```
This should fix those errors for fabric/legacy-fabric/quilt servers, cause they are only ones using mkTextileLoader.

Related to issues #79 and #83, and pull request #80

2024-07-24 13:14 UTC, mechan1sm commented
Also, during testing I found that [quilt loader 0.17.5-beta.4 has broken versions in its loader_locks.json](https://github.com/Infinidoge/nix-minecraft/blob/master/pkgs/quilt-servers/loader_locks.json#L2866).
(Tested only version evaluation for fabric/fabric-legacy/quilt servers. The only one that errors is quilt 0.17.5-beta.4)

2024-07-25 04:14 UTC, Infinidoge requested changes
Haven't tested the packages of this myself yet, just a small code style nitpick. Overall looks good to me. I'm not the biggest fan of using regex to solve this, and think this is the kind of thing that should be handled in the update scripts/lock files, however this works as a quick fix that just solves the problem, especially without needing to process the lockfiles to backfill information.

2024-07-25 04:14 UTC, Infinidoge commented on pkgs/build-support/mkTextileLoader.nix
> +  ));
```suggestion
let
  inherit (builtins) head filter map match;
  
  lib_lock = lib.importJSON ./libraries.json;
  fetchedLibraries = lib.forEach libraries (l: fetchurl lib_lock.${l});
  asmVersion = head (head (filter (v: v!=null) (map (match "org\\.ow2\\.asm:asm:([\.0-9]+)") libraries)));
```

Bit of cleanup, all of the `builtins` was just noise.

2024-07-25 04:20 UTC, Infinidoge commented
Also as a note with regards to #84, I squash pull requests, so you didn't need to recreate the PR to turn it into 1 commit. (Could also rebase/squash yourself, but that takes git knowledge most people avoid lol)

2024-07-30 02:18 UTC, Infinidoge commented
Please avoid merging the master branch into PR branches, and rebase instead. It clutters the history and can get messy with squash merging.

2024-07-30 11:58 UTC, mechan1sm commented
Ah, github "sync fork" feature performs merge instead of rebase. Will you merge this PR? Should I revert this merge commit and rebase, or do something else?

2024-07-30 12:33 UTC, Infinidoge commented
Go ahead and rebase on master, and it should theoretically remove the merge commits automatically.

2024-08-08 22:14 UTC, Infinidoge approved these changes

2024-08-08 22:23 UTC, Infinidoge commented
Running the VM tests before merging.

2024-08-08 22:35 UTC, merged