Document overriding with custom server jar
Infinidoge/nix-minecraft pull request #98
Opened 2024-08-30 15:09 UTC by JimmJam

Some server jar files are either too niche to be merged into the project, or make my head spin on even attempting to get officially merged with the Python scripting involved to do so. However, I've found it's very easy to override the src of the vanilla server's package to support custom jar files. My small contribution is documenting how to do so and letting people know it's possible :)

2024-09-01 03:05 UTC, Infinidoge commented
Good catch!

That said, to me this feels like a small hole in the libraries that could be improved on. Something like a `buildServer` helper that accepts a `jar` argument, perhaps.

2024-09-01 03:06 UTC, Infinidoge requested changes
Add a note clarifying that this sets the path to the jar in a launch script (and not actually modifying a vanilla server), and this should be good to go

2024-09-16 18:50 UTC, JimmJam reviewed
Added the comment about overriding path, not jar

2024-09-19 19:28 UTC, Infinidoge requested changes
Couple small nitpicks (which you can commit right from GitHub, and this is good to merge :)

At some point I'll probably add a build tool for this so it doesn't need to be done with an override, but that's a later problem.

2024-09-19 19:28 UTC, Infinidoge commented on README.md
> +Server versions not found above can be manually via an override.
```suggestion
Server versions not found above can be setup manually via an override.
```

2024-09-19 19:28 UTC, Infinidoge commented on README.md
> +In this example, uberbukkit.jar exists next to this configuration:
```suggestion
For example, this override changes the path the launch script uses to your provided jar file, and does not modify the vanilla jar:
```

I don't think it's necessary to specify that the jar is alongside, since that should be implicit in how the code is written.

2024-09-22 23:32 UTC, merged